name: pixels2flutter
description: Convert a screenshot to a working Flutter app.
version: 1.0.0+1
publish_to: 'none'

environment:
  sdk: 3.1.5
  flutter: 3.13.9

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter

  dotted_border:
  equatable:
  file_picker:
  flutter_animate:
  flutter_bloc:
  flutter_secure_storage:
  flutter_svg:
  freezed_annotation:
  get_it:
  github:
  go_router:
  injectable:
  langchain:
  langchain_openai:
  flutter_markdown:
  result_dart:
  super_drag_and_drop:
  syntax_highlight:
  url_launcher:
dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner:
  flutter_gen_runner:
  freezed:
  injectable_generator:

flutter:
  uses-material-design: true
  assets:
    - assets/

flutter_gen:
  output: lib/app/assets
  integrations:
    flutter_svg: true
  assets:
    enabled: true
  fonts:
    enabled: false
  colors:
    enabled: false
